### ISSUE TITLE
EDD Blocks: Avoid using !important in block styles

### ISSUE THREAD

**Issue by dashkevych** [awesomemotive/easy-digital-downloads#9598]
### Explain your enhancement (please be detailed)
Please avoid using `!important` in styles for blocks since it makes hard to override default styles.

### Justification or use case
For instance, the Login block uses the following CSS:

```css
.edd-blocks-form .edd-blocks-form__group > label {
  display: block;
  margin-bottom: .5rem !important;
}
```

So, for some sites 0.5rem might be a good spacing but not all website are the same.

Also, use of `!important` is considered [bad practice](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception).
